### ISSUE TITLE
Linting check on push rather than on commit

### ISSUE THREAD

**Issue by nohe427** [chromeos/chromeos.dev#140]
**Is your feature request related to a problem? Please describe.**
Yes, I write an article, I make some changes, I commit those changes, and then when I push the linting fails and I need to re commit my changes after linting.

**Describe the solution you'd like**
If we are going to block on linting, it would be helpful to do that on commit because the commit workflow takes awhile.

**Describe alternatives you've considered**
`git commit --amend --no-edit` -> This does not work though because husky still runs and the command creates a new commit anyways.

**Additional context**
none

**Comment by Snugug** [comment]
## Commit Messages
Consider migrating to GitHub [automatic release notes)[https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes] and maybe something like [PR title checker](https://github.com/marketplace/actions/pr-title-checker) to resolve the usecase we had for being strict with commit messages. 

## Linting
Consider using [lint staged](https://github.com/okonet/lint-staged)

**Comment by Snugug** [comment]
Started because Husky is currently failing with our current setup due to this.

**Comment by Snugug** [comment]
Closed w/#173
