### ISSUE TITLE
New Vite Service Worker Plugin

### ISSUE THREAD

**Issue by Snugug** [chromeos/chromeos.dev#151]
Current SW compilation from [Vite Plugin PWA](https://www.npmjs.com/package/vite-plugin-pwa) doesn’t meet the following core needs:
- [x] Manipulation (filtering, additions, etc…) of files for Workbox’s InjectManifest precache (so we don’t have to precache every single generated Vite file)
- [ ] Not requiring [Workbox Window](https://developers.google.com/web/tools/workbox/modules/workbox-window) to register a Service Worker
- [ ] Not requiring InjectManifest to compile service worker (for [Workbox Recipes](https://www.npmjs.com/package/workbox-recipes) compatibility)
- [ ] Option for [chunkFileNames](https://rollupjs.org/guide/en/#outputchunkfilenames) to not include a hash
- [ ] Ability to test Service Workers [during development](https://github.com/vitejs/vite/issues/2248) (optional)

**Comment by Snugug** [comment]
May icebox this if https://github.com/antfu/vite-plugin-pwa/issues/192 lands

**Comment by userquin** [comment]
@Snugug I'm also interested on trying to fix this list, we can fix it, PR are welcome on the plugin, some hints:

1) you can use `globPatterns` and `globIgnores`
2) I need to review the plugin, but I think you don't need to use the virtual module `virtual:pwa-register` (using workbox-window)
3) uhmm, maybe we can add another strategy for it, since the service worker is compiled, we only need to omit the `injectManifest` part
4) I think this option should be done via vite configuration
5) I have some branch on my fork with some tests to allow test on development.

**Comment by userquin** [comment]
@Snugug the repo and branch for sw on development can be found here https://github.com/userquin/vite-plugin-pwa/tree/feat/add-development-support

Just check the last plugin on `src/index.ts` module and the logic on `src/dev.ts` module.

**Comment by userquin** [comment]
@Snugug you can use `injectRegister: null` for entry 2, see description here: https://github.com/antfu/vite-plugin-pwa/blob/main/src/types.ts#L47

**Comment by userquin** [comment]
for 1) you can also use `transformManifest`

**Comment by userquin** [comment]
FYI: working on a new strategy to compile custom typescrypt sw

**Comment by Snugug** [comment]
Thanks to the above comments, and a rethink of how we may implement our SW, I think our implementation can move from creating a new SW plugin to improving how we use Vite PWA today. There are still some areas (like local development) where there is work needed, but we can survive without it right now.

**Comment by userquin** [comment]
@Snugug just check this https://github.com/jeffposnick/yt-playlist-notifier/issues/2, using custom sw on development

**Comment by userquin** [comment]
@Snugug pwa plugin released `0.11.13'  with development support

**Comment by userquin** [comment]
@Snugug do you need to build only the service worker?
