### ISSUE TITLE
Can't use backspace in chrome os emulator

### ISSUE THREAD

**Issue by noahsalvadordenjo** [chromeos/chromeos.dev#165]
Backspace isn't working in the chrome os emulator or it depends on flutter i've run flutter doctor -v without any problems

**Comment by Snugug** [comment]
Hey, thanks for your bug report!

This issues tracker is for chromeos.dev, not Chrome OS in general. Can you please file your bug in the [Chrome OS issue tracker](https://bugs.chromium.org/p/chromium/issues/list) to make sure it gets routed to the right team to help resolve it?

Thank you!
