### ISSUE TITLE
Share record screen on youtube

### ISSUE THREAD

**Issue by noahsalvadordenjo** [chromeos/chromeos.dev#166]
Hi i would like to share my screen and microphone on youtube. i've downloaded obs but that only gave me a black screen.
Could you update chrome os to share on youtube and other streaming platforms?

**Comment by Snugug** [comment]
Hey, thanks for your question!

This issues tracker is for chromeos.dev, not Chrome OS in general. Can you please file your request in the [Chrome OS issue tracker](https://bugs.chromium.org/p/chromium/issues/list) to make sure it gets routed to the right team to answer this?

Thank you!
