### ISSUE TITLE
On wich port does the screen recorder listen

### ISSUE THREAD

**Issue by noahsalvadordenjo** [chromeos/chromeos.dev#167]
due to https://github.com/chromeos/chromeos.dev/issues/166 i might found a solution next to obs his black screen and streamlabs audio problem I found this article 
https://linuxforever.info/2017/05/06/how-to-live-stream-to-youtube-from-linux-mint-ubuntu/
and i'm only wondering on wich port does the screen recorder listen or what is his location so i can replace https://gist.github.com/olasd/9841772 the source with?

**Comment by Snugug** [comment]
Hey, thanks for your question!

This issues tracker is for chromeos.dev, not Chrome OS in general. Can you please file your request in the [Chrome OS issue tracker](https://bugs.chromium.org/p/chromium/issues/list) to make sure it gets routed to the right team to answer this?

Thank you!
