### ISSUE TITLE
How to turn of default firewall?

### ISSUE THREAD

**Issue by noahsalvadordenjo** [chromeos/chromeos.dev#171]
Hi i would like to turn of my firewall on a chromebook or is this already possible could you tell me how?

**Comment by Snugug** [comment]
Hey, thanks for your question!

This issues tracker is for chromeos.dev, not Chrome OS in general. Can you please file your request in the [Chrome OS issue tracker](https://bugs.chromium.org/p/chromium/issues/list) to make sure it gets routed to the right team to answer this?

Thank you!
