### ISSUE TITLE
Add redirect for /subscribe

### ISSUE THREAD

**Issue by Snugug** [chromeos/chromeos.dev#249]
/subscribe should redirect to en/subscribe

**Comment by nohe427** [comment]
Should this work for all doc links etc... https://chromeos.dev/publish/play-console-setup-for-billing should redirect to the en version?

**Comment by Snugug** [comment]
Redirects unfortunately need to be manually configured through Firebase, so we're only going to do redirects for key pages

**Comment by Snugug** [comment]
Superseded by #520
