### ISSUE TITLE
Module: Video Cards

### ISSUE THREAD

**Issue by monkishtypist** [chromeos/chromeos.dev#263]
Design: https://www.figma.com/file/xtBKZcRBo7H2Jrjs7DjNqE/Final-Designs?node-id=2%3A4714

**Comment by nickalcantara** [comment]
Adjustment from Design:

When clicked, Video Cards should open in a modal with the Youtube video player embed. The modal should be aligned to the [Google Store homepage modal](https://store.google.com/) that can be seen by clicking the "Watch Video" CTA.

Once the modal is opened, the embed should begin playing without a second user action.
