### ISSUE TITLE
Flexible Shapes Component

### ISSUE THREAD

**Issue by nickalcantara** [chromeos/chromeos.dev#319]
A flexible component is needed to handle the variety of shapes used throughout the homepage redesign. This component would ideally allow for masks, textures, colors, and potentially transforming or scaling.

I've prototyped using multiple options (existing circles worklet, pseudo elements, color stops, SVGs, etc), but each option has limitations or concerns such as overhead or a lack of reusability. 

Designs: https://www.figma.com/file/o9JHnISo2QrwyiKvLyRGys/Chrome-OS-Redesign-%5BFINAL%5D?node-id=2%3A4430

Modules that will use flexible shapes:
- Interstitial Banner (#212)
- Routing Cards (#209)
- Fifty Fifty (#262)

**Comment by monkishtypist** [comment]
Updated design link: https://www.figma.com/file/xtBKZcRBo7H2Jrjs7DjNqE/Final-Designs?node-id=0%3A1

**Comment by Snugug** [comment]
Ok! I've gone down the paint worklet path and created a "shapes" worklet that can have a triangle, circle, or "moon" drawn, with each allowing for absolute or relative sizing, rotation, offset, and of course, color. Multiple shapes can be drawn by passing multiple values into the custom properties. (screenshots below)

Question: should I investigate also doing our patterns this way? It'd likely wind up having me look into using [clipping paths](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Compositing#clipping_paths) (presuming they work in worklets)?

![Screenshot of Pain worklet with two shapes drawn and the accompanying CSS to draw them](https://user-images.githubusercontent.com/377188/158686452-9d9467fe-e7e6-4745-bd86-332fc380cc16.png)

![Area with three overlapping shapes drawn from a paint worklet](https://user-images.githubusercontent.com/377188/158686528-9eb59e3f-ecd7-492e-9e1d-ce9fc7d26db3.png)
