### ISSUE TITLE
Back to top button not being rendered

### ISSUE THREAD

**Issue by nohe427** [chromeos/chromeos.dev#321]
**Describe the bug**

A back to top button should be visible on the pages.

**To Reproduce**

1. Go to https://chromeos.dev/en/posts/android-package-signer
2. Scroll down to the bottom of the page
3. No back to top button is being rendered.

**Expected behavior**
A back to top button should be rendered and visible on the page.

**Desktop (please complete the following information):**

- OS: [e.g. iOS] macOS
- Browser [e.g. chrome, safari] Chrome
- Version [e.g. 22] 99

**Comment by Snugug** [comment]
The back to top button is only visible <900px, and on the current site I do see it rendering when the screen size is below that cutoff point. Is this that it's not showing at all, including below that breakpoint, or that you'd like it to always be visible?

**Comment by staranbeer** [comment]
the button only being visible below on displays below 900px feels a bit weird,w shouldn't it be visible on all screen sizes?
