### ISSUE TITLE
Determine how to provide related content for items from the CMS

### ISSUE THREAD

**Issue by Snugug** [chromeos/chromeos.dev#528]
Initial thoughts:

- MVP of this could be a `postbuild` script that runs our existing indexing code and spits back a search index that we then search against to provide related content. Keep everything else the same
- Alternatively, we could add a specific "related content" field that's manually curated
- The 1st solution may not work in dev or staging

**Comment by Snugug** [comment]
[Ranked search](https://github.com/sanity-io/sanity/issues/1444) from the Sanity API may be good enough here

**Comment by doublejosh** [comment]
Here's how to suggest relevant content based on category tags in a field...
https://www.sanity.io/schemas/related-content-9079f69e
