### ISSUE TITLE
Menu quebra ao traduzir página para Português Brasil

### ISSUE THREAD

**Issue by KelvinLopes** [chromeos/chromeos.dev#53]
Olá pessoal, tudo bem?
Em minha visita ao chromeos.dev, observei que o menu quebra ao traduzir para o Português Brasil, em algumas páginas dificulta ler o primeiro título.

Sistema:  **_Chrome_** **_OS_**, versão 85.0.4183.59, canal _beta_
Dispositivo: _**Samsung Chromebook 3**_
Navegador: _Chrome padrão._

**Comment by Snugug** [comment]
(sorry for responding in English, I [translated your comment](https://translate-prod.sandbox.google.com/?sl=auto&tl=en&text=Ol%C3%A1%20pessoal%2C%20tudo%20bem%3F%0AEm%20minha%20visita%20ao%20chromeos.dev%2C%20observei%20que%20o%20menu%20quebra%20ao%20traduzir%20para%20o%20Portugu%C3%AAs%20Brasil%2C%20em%20algumas%20p%C3%A1ginas%20dificulta%20ler%20o%20primeiro%20t%C3%ADtulo.%0A%0ASistema%3A%20Chrome%20OS%2C%20vers%C3%A3o%2085.0.4183.59%2C%20canal%20beta%0ADispositivo%3A%20Samsung%20Chromebook%203%0ANavegador%3A%20Chrome%20padr%C3%A3o.&op=translate) so I think I understand what you're requesting).

Thanks for the feedback! If you could provide a screen shot of what you're seeing and steps we can follow to reproduce your translation that'd be really helpful for us to debug. Our site currently officially supports English and Spanish, so we know it works well in those languages, but will work on reproducing your issue and see if we can improve the experience for other types of translations a user may do!

Thanks!

**Comment by KelvinLopes** [comment]
![Screenshot 2020-08-15 at 12 12 27](https://user-images.githubusercontent.com/38872754/90445532-3240d200-e0b6-11ea-92dd-f3f26128d779.png)

Obrigado pelo feedback.  Eu também traduzi sua resposta.  Estou usando uma ferramenta de tradução, ainda estou aprendendo inglês.  Eu acho que você acertou.  Esta é uma captura de tela para ilustrar o que aconteceu.

Thanks for the feedback.  I also translated your answer.  I'm using a translation tool, I'm still learning English.  I think you got it right. This is a screenshot to illustrate what happened.

**Comment by Snugug** [comment]
Thank you! We'll take a look!

Obrigado! Vamos dar uma olhada!
