### ISSUE TITLE
A script for AppImage installation for the Linux environment.

### ISSUE THREAD

**Issue by nathanielstenzel** [chromeos/chromeos.dev#557]
There does not seem to be any native handling of AppImage files so I wrote a script to copy the stuff to the /usr/local/bin and put the .desktop file in /usr/share/applications with the Exec line changed to refer to the AppImage line. Please feel free to use my script so that other ChromeOS users do not struggle with this.
https://gist.github.com/nathanielstenzel/4196b877dd1a3159cda69bec4e6d66eb
If you were to make a .desktop file editor/creator of your own, I suppose that would work too.

**Comment by TomTravis** [comment]
yes cool

**Comment by Snugug** [comment]
Thanks for sharing your script! If you'd like to see better AppImage support, please file an issue on the [ChromeOS bug tracker](https://bugs.chromium.org/p/chromium/issues/entry?template=Defect+on+Chrome+OS) so someone from the engineering team can take a look (this is just for the website).

Thanks!

**Comment by nathanielstenzel** [comment]
Wait....you told me to post on a WEB BROWSER's bug tracking? This script is for the CHROME OS. It is NOT for the Chrome BROWSER. It is for making files that need to be in certain places for things to work.

**Comment by nathanielstenzel** [comment]
"https://github.com/chromeos/chromeos.dev Public
chromeOS.dev is the digital home for all things ChromeOS. Learn how to adapt and optimize your existing apps to work on ChromeOS, the success other companies have had doing so, how to use ChromeOS as your developer machine, and keep up-to-date with the latest on ChromeOS."

An AppImage is a collection of files (I think it was inside a ZIP file but with a different extension) that runs on a Linux system such as ChromeOS which is basically Android which is a bastardized Linux with a Java stack on top. So, getting an AppImage to work on ChromeOS fits the description of this section.
