### ISSUE TITLE
permission exec mounts

### ISSUE THREAD

**Issue by TomTravis** [chromeos/chromeos.dev#559]
**Describe the bug**
bash: /usr/local/bin/test.sh: Permission denied
https://chromium.googlesource.com/chromiumos/docs/+/master/security/noexec_shell_scripts.md

**To Reproduce**
run example this should work in v106 this did work
in v107 is does not work
this is google example how to use the computer
security has done something not documented
chronos@localhost /usr/local/bin $ more mnt.sh
sudo mount -o remount,symfollow -o exec /media/removable/sd200
sudo mount -o remount,symfollow -o exec /tmp    
sudo mount -o remount,symfollow -o exec /var/run
sudo mount -o remount,symfollow -o exec /
chronos@localhost /usr/local/bin $ mnt.sh
Password: 
works

printf '#!/bin/sh\necho hi\n' > /usr/local/bin/test.sh
fail
chmod a+rx /usr/local/bin/test.sh
which test.sh
/usr/local/bin/test.sh test.sh
hi

**Expected behavior**
the sh file should run like mnt.sh does
writing to a file via printf fails
write to a file using 
tee works

**Screenshots**

**Desktop (please complete the following information):**
Version 107.0.5304.110 (Official Build) (32-bit)
![Screenshot 2022-11-17 12 07 41 PM](https://user-images.githubusercontent.com/46386261/202548621-1252cd7f-c026-4007-a239-18e4743a8616.png)

**Smartphone (please complete the following information):**

- you have this chome://system screen shot

**Additional context**

chronos@localhost /usr/local/bin $ sudo printf '#!/bin/sh\necho hi\n' >>test.sh
bash: test.sh: Permission denied
chronos@localhost /usr/local/bin $ sudo vi /usr/local/bin/test.sh 
chronos@localhost /usr/local/bin $ test.sh
bash: /usr/local/bin/test.sh: Permission denied
chronos@localhost /usr/local/bin $ sudo chmod 777 test.sh
chronos@localhost /usr/local/bin $ test.sh
#!/bin/sh
echo hi
chrosh shell screen shot
chronos@localhost /usr/local/bin $ 
![Screenshot 2022-11-17 11 58 01 AM](https://user-images.githubusercontent.com/46386261/202546621-da9bc7a8-415d-43a3-b6ce-29357b7bc378.png)

**Comment by TomTravis** [comment]
hello
it appear 
sudo touch z.sh 
sudo chmod 777 z.sh
sudo printf '#!/bin/sh\necho hi\n' >>z.sh
z.sh 
works
so the file must exist inorder to write and exec it
now all my shell must have a touch test prior to printf
thank goodness for vscode and juypterlab

**Comment by TomTravis** [comment]
let keep this open for other comments

**Comment by TomTravis** [comment]
hello the exec is now running in /usr/local/bin 
V106 i hope the repairs the no permission issues
![Screenshot 2022-11-18 3 38 48 PM](https://user-images.githubusercontent.com/46386261/202821493-2226e987-e6eb-44b7-ac78-efc16c6df5cc.png)

**Comment by TomTravis** [comment]
well sed and update 2022 happened today 
let hope it installs on 107..109 for people now running all in /usr/local/bin for install and update
![Screenshot 2022-11-19 4 32 39 PM](https://user-images.githubusercontent.com/46386261/202877503-aec0b89e-a8ce-49a8-8095-c176bf881ea5.png)

**Comment by TomTravis** [comment]
great test2 is working change exec to /usr/local/bin
mnt /usr/local exec,dev
https://github.com/dnschneid/crouton/issues/4878
people are developing again wonderful news

**Comment by TomTravis** [comment]
happy holiday
Hello,

Thanks for reaching out to us.

We have received your request.

We receive many such requests each day; your message is in our queue, and we'll get to it as quickly as our workload permits. Due to the large volume of requests that we receive, we will only be able to provide you with a response if we determine your request may be a valid and actionable legal complaint, and we may respond with questions or requests for clarification. For more information on Google's Terms of Service, please visit http://www.google.com/accounts/TOS

Regards,

The Google Team

Due to the impact of COVID-19, it may take us longer than usual to respond to your request. Our apologies for the inconvenience.

**Comment by Snugug** [comment]
Thank you for reaching out to us! It looks like this is an issue with ChromeOS itself instead of the website. Please file a bug [here](https://bugs.chromium.org/p/chromium/issues/entry?template=Defect+on+Chrome+OS) so it can get into the hands of our OS engineers.

Thanks!
