### ISSUE TITLE
Console errors in Chrome packaged app when Chrome version is 109 or higher 

### ISSUE THREAD

**Issue by findsujay** [chromeos/chromeos.dev#605]
**Description**
We have an Angular app on Angular 10, which loads within a Chrome packaged app. This setup has been running well so far, but ever since Chrome version 109 (specifically, 109.0.5414.125) we are seeing console errors. 

The console errors show `history.pushState is not available in packaged apps` and `history.length is not available in packaged apps`. Our app does not use either `history.pushState` or `history.length`; and we suspect this is being caused because the Angular router is somehow running afoul of the Chrome OS update. 

**To Reproduce**

- I created a sample project to demonstrate this at https://github.com/findsujay/chrome-packaged-angular-sample.
- Please follow the directions in the sample project to build, deploy and test the issue. I have also provided a ready-to-deploy build here: https://ipos-ui-shared-bucket.s3.amazonaws.com/public_assets/Misc/Chrome-history-error/chrome-package-0214.zip
- When you launch the app in Chrome OS, you will see 2 errors:
-- Error 1: history.pushState is not available in packaged apps
-- Error 2: Cannot match any routes. URL Segment: 'index.html'
- As observed above, the issue only occurs when Chrome OS version is 109 or higher. When Chrome version is 108 or lower, there are no errors.

**Expected behavior**
Even when using Chrome OS version 109 or higher, there should be no console errors for the provided app.

**Desktop (please complete the following information):**
- OS: Chrome OS 109 and higher
- Browser: This is a packaged app

**Additional context**
Please note:
1. The issue does not occur for Chrome OS version 108 and lower.
2. We are aware that Chrome packaged apps are on their way out. Google has announced they will sunset support for them in 2024 for Chrome OS, and we will be moving to an alternative platform. Until then we need to keep the production app running.
3. This issue occurs in the latest version of Angular (v15) as well, so Angular version is not an issue. We do plan on upgrading to ng15, but that will not help for this issue.

**Comment by Snugug** [comment]
Thanks for your feedback here! This issue tracker is for ChromeOS.dev, our developer-focused documentation and news site. This unfortunately doesn't look like it belongs here. If you're looking to report a bug or request a feature for ChromeOS, please [report a ChromeOS problem or send feedback](https://support.google.com/chromebook/answer/2982029?hl=en) instead, or [report a ChromeOS bug](https://www.chromium.org/chromium-os/developer-library/guides/bugs/reporting-bugs/) directly.
