### ISSUE TITLE
Unable to Start Virtualbox due to missing linux-headers

### ISSUE THREAD

**Issue by sheastech** [chromeos/chromeos.dev#608]
**Describe the bug**
Unable to locate linux headers for linux-headers-5.10.159-20950-g3963226d9eb4
Unable to install Virtualbox on the Debian 11 container of the Linux dev environment

**To Reproduce**

1. Install the Linux container for Debian
2. Open the terminal and verify the kernel and OS

dunyacorp@penguin:~$ uname -r
5.10.159-20950-g3963226d9eb4

dunyacorp@penguin: cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
dunyacorp@penguin:~$ 

dunyacorp@penguin: apt search linux-headers-$(uname -r)
Sorting... Done
Full Text Search... Done
dunyacorp@penguin:~$ ls -l /usr/src/linux-headers-$(uname -r)
ls: cannot access '/usr/src/linux-headers-5.10.159-20950-g3963226d9eb4': No such file or directory

Unable to locate headers. Enable root login and verify from root that configuration is actually there.

sudo vi /etc/ssh/sshd_config (enable the  PermitRootLogin yes #enabled)

reboot the system. 
su to root 

apt search linux-headers | grep linux-headers

**Expected behavior**
I should be able to install the headers like normal in Debian OS
sudo apt install linux-headers-$(uname -r)
ls -l /usr/src/linux-headers-$(uname -r)

**Screenshots**

![image](https://user-images.githubusercontent.com/31675952/224202114-aac756e3-50cf-43f9-aa83-f293eb14cc93.png)
![image](https://user-images.githubusercontent.com/31675952/224202228-16ff746a-2975-4793-bdfc-4fb736c4c4a0.png)
![image](https://user-images.githubusercontent.com/31675952/224202350-55177e97-2e03-4055-a5d0-c446d798be6b.png)

**Desktop (please complete the following information):**

- OS: Chromebook
- Browser Chrome
- Version: Version 110.0.5481.181 (Official Build) (64-bit)
- ASUS - 16" 2-in-1 Touchscreen Chromebook - Intel Core i3 - 8GB Memory - 128GB SSD - Mineral Grey

Google ChromeOS | 110.0.5481.181 (Official Build) (64-bit)

Revision | 712d9367cf24bad88a7077390abaa1b60212730d-refs/branch-heads/5481@{#1245}
Platform | 15278.72.0 (Official Build) stable-channel brya
Firmware Version | Google_Felwinter.14505.266.0
Customization ID | felwinter
ARC | 9586199 SDK Version: 30
JavaScript | V8 11.0.226.16
User Agent | Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36

**Additional context**
commands run to install and fix virtualbox itself

sudo dpkg -i virtualbox-7.0_7.0.6-155176_Debian_bullseye_amd64.deb
sudo apt-get --fix-broken install
sudo apt-get update

Unable to run Virtualbox due to this problem with the headers. 
This header (assuming it's custom) is not on the Debian website: https://packages.debian.org/search?keywords=search (at least have a Google one if your going to customize the OS if that is the case).

**Comment by Snugug** [comment]
Thanks for your feedback here! This issue tracker is for ChromeOS.dev, our developer-focused documentation and news site. This unfortunately doesn't look like it belongs here. If you're looking to report a bug or request a feature for ChromeOS, please [report a ChromeOS problem or send feedback](https://support.google.com/chromebook/answer/2982029?hl=en) instead, or [report a ChromeOS bug](https://www.chromium.org/chromium-os/developer-library/guides/bugs/reporting-bugs/) directly.
