### ISSUE TITLE
Invalid link on ChromeOS 116 release notes

### ISSUE THREAD

**Issue by tatsumi33** [chromeos/chromeos.dev#648]
**Describe the bug**
There is an invalid link on ChromeOS 116 releases notes.

https://github.com/chromeos/chromeos.dev/blob/ee68fd08c2abe4ebd2e3fa6c16ad5f519403432f/site/en/posts/chromeos-116-release-notes.md?plain=1#L21

`a long standing [feature request](https://b.corp.google.com/issues/149234835). `

**To Reproduce**

1. Go to https://chromeos.dev/en/posts/chromeos-116-release-notes#expanded-language-and-emoji-support-for-linux-apps
2. Click on 'feature request'
3. Signin page will be opened

**Expected behavior**
It shows the feature request page.

**Screenshots**
n/a

**Desktop (please complete the following information):**

- OS: ChromeOS 116
- Browser Chrome
- Version 116

**Additional context**
n/a

**Comment by Snugug** [comment]
You need to sign into Buganizer in order to see the feature request, unfortunately resolving that is beyond the scope of what we're capable of doing. The bug itself is publicly visible if logged in.
