### ISSUE TITLE
Unicode 15.0 Emojis can't be searched on emoji picker

### ISSUE THREAD

**Issue by bsoap-cat** [chromeos/chromeos.dev#664]
As the title of this issue says, all of the emojis added to Unicode 15.0 cannot be searched within the emoji picker. This bug has existed for quite a while now, existing when it was first implemented into an update.

1. Press Shift + Search + Space to open the emoji picker
2. Hover to an emoji that was added to Unicode 15.0 (use U+1FAE8 🫨 Shaking Face as an example)
3. Try searching for the emoji's name (type in "shaking face" as an example)

**Expected behavior**
The emoji should have a name when hovering over it and should be searchable in the search bar.

**Screenshots**
![image](https://github.com/chromeos/chromeos.dev/assets/127647009/89a9ec86-2982-4260-891d-0a363f75f74b)

Since your cursor can't be seen in an image when taking a screenshot on ChromeOS, I won't be showcasing the image here.

**Comment by akshayrajput12** [comment]
I will like to work on this issue sir @bsoap-cat

**Comment by bsoap-cat** [comment]
the bug has been fixed
