### ISSUE TITLE
file extension .jpe

### ISSUE THREAD

**Issue by mikkelmogensen** [chromeos/chromeos.dev#671]
.jpe is not used often but in my files .jpe should be recognized as as image

i have not tested .mpe which should be recognized as a video

**Comment by Snugug** [comment]
Thanks for your feedback here! This issue tracker is for ChromeOS.dev, our developer-focused documentation and news site. This unfortunately doesn't look like it belongs here. If you're looking to report a bug or request a feature for ChromeOS, please [report a ChromeOS problem or send feedback](https://support.google.com/chromebook/answer/2982029?hl=en) instead, or [report a ChromeOS bug](https://www.chromium.org/chromium-os/developer-library/guides/bugs/reporting-bugs/) directly.
