### ISSUE TITLE
Android ARCVM container and AV1 hardware decoding

### ISSUE THREAD

**Issue by Jejebond** [chromeos/chromeos.dev#681]
**Is your feature request related to a problem? Please describe.**
When i try AV1 hardware decoding on my Chromebook with the Moonlight Client Android app, it steps back to HEVC. My chromebook (Asus Cx5500, i5 11th gen) can handle AV1 hardware decoding. Moonlight doesn't have a stable and up to date native webapp to test.

**Describe the solution you'd like**
Android ARCVM container only seems to handle software decoding, whitch Moonlight ignores (for good reasons : latency).
Android ARCVM container handles hardware decoding for HEVC. An hardware implementation of AV1 is missing. Is it linked to the android version used in the container ? I don't see any flags about this (running ChromeOS 119.0.6045.192 stable. I've tested the beta with ARCVM 13, same issue.

Is there a way to check if natively (not through the Android container), my Chromebook can handle AV1 Hardware decoding ? I know the i5 11th gen can do it, but does it really on ChromeOS ?

**Additional context**
![Screenshot 2023-12-09 08 13 44](https://github.com/chromeos/chromeos.dev/assets/3942165/966785a8-fe8a-49c4-84a7-8a5983e2bd35)

**Comment by Snugug** [comment]
Thanks for your feedback here! This issue tracker is for ChromeOS.dev, our developer-focused documentation and news site. This unfortunately doesn't look like it belongs here. If you're looking to report a bug or request a feature for ChromeOS, please [report a ChromeOS problem or send feedback](https://support.google.com/chromebook/answer/2982029?hl=en) instead, or [report a ChromeOS bug](https://www.chromium.org/chromium-os/developer-library/guides/bugs/reporting-bugs/) directly.
