### ISSUE TITLE
Error in code "Warpper" instead of "Wrapper"

### ISSUE THREAD

**Issue by purrrlin** [chromeos/chromeos.dev#69]
I noticed an error while browsing the code, it says `warpper` instead of `wrapper` on line 12 here.

https://github.com/chromeos/chromeos.dev/blob/af190cc961f3f7bca4208941d2c272edeae35a3a/pages/_generated/offline.html#L12

**Comment by Aditya8840** [comment]
Hey @Snugug, I would like to work on this issue. Can you please assign me?
