### ISSUE TITLE
Badge Guidelines Singleton

### ISSUE THREAD

**Issue by nickalcantara** [chromeos/chromeos.dev#699]
Implement a badge guidelines singleton within Sanity following the existing convention for other singletons.

**Comment by nickalcantara** [comment]
@Snugug It looks like the badge guidelines document should be created via [createSingletons](https://github.com/chromeos/chromeos.dev/blob/refactor/the-great-cms-migration/cms/scripts/createSingletons.ts). The comments in the function indicate that content is lost anytime the function is run. Is this a concern if ran within the development dataset? Shall we create the singleton document a different way?

**Comment by Snugug** [comment]
Done
