### ISSUE TITLE
VT-2, Crostini and Dualsense

### ISSUE THREAD

**Issue by NazarychUA** [chromeos/chromeos.dev#709]
I need your help! I have a Chromebook Spin 514. I have Dualsense. Applications installed using the Penguin virtual machine do not see the gamepad. As I discovered, Penguin has limitations. I want to somehow influence the Penguin through the VT-2 terminal. I'm currently in developer mode. Tried to install the dev package for the "emerge" command. Not everything goes smoothly. Also failed to install the Nano text editor. I will be grateful for any advice and help. With best regards.

**Comment by Snugug** [comment]
Thanks for your feedback here! This issue tracker is for ChromeOS.dev, our developer-focused documentation and news site. This unfortunately doesn't look like it belongs here. If you're looking to report a bug or request a feature for ChromeOS, please [report a ChromeOS problem or send feedback](https://support.google.com/chromebook/answer/2982029?hl=en) instead, or [report a ChromeOS bug](https://www.chromium.org/chromium-os/developer-library/guides/bugs/reporting-bugs/) directly.
