### ISSUE TITLE
please add a package manager

### ISSUE THREAD

**Issue by YeesterPlus** [chromeos/chromeos.dev#717]
**Describe the solution you'd like**
apt like package manager

**Describe alternatives you've considered**
chromebrew

```[tasklist]
### Tasks
- [ ] package format
- [ ] dependencey manager
- [ ] repository
- [ ] package manager
```

**Comment by Snugug** [comment]
Thanks for your feedback here! This issue tracker is for ChromeOS.dev, our developer-focused documentation and news site. This unfortunately doesn't look like it belongs here. If you're looking to report a bug or request a feature for ChromeOS, please [report a ChromeOS problem or send feedback](https://support.google.com/chromebook/answer/2982029?hl=en) instead, or [report a ChromeOS bug](https://www.chromium.org/chromium-os/developer-library/guides/bugs/reporting-bugs/) directly.
